1:
  statement: What is one plus one
  options:
      a: 1
      b: Beer
      c: 2
  answer: 2
2:
  statement: What is one plus one
  options:
      a: 1
      b: Beer
      c: 2
  answer: 2
3:
  statement: What is one plus one
  options:
      a: 1
      b: Beer
      c: 2
  answer: 2
4:
  statement: What is one plus one
  options:
      a: 1
      b: Beer
      c: 2
  answer: 2
5:
  statement:
    Which one is better
    ![icon](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 1")
  options:
      a: foo
      b: var
      c: beer
  answer: beer
6:
  statement: What is one plus one
  options:
      a: 1
      b: Beer
      c: 2
  answer: 2
